
package librairie2;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import packageClient.Client;

public final class FrameClient extends javax.swing.JFrame {

    public FrameClient() {
        initComponents(); 
        montrer_client();
        setTitle("BACK-OFFICE LIBRAIRIE RANDRIA JEFF");
    }
    public ArrayList<Client> clientList() {
        ArrayList<Client> clientsList = new ArrayList();

        try  {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url ="jdbc:sqlserver://localhost:1433;databaseName=Librairie;"
                    + "user=sa;password=sa";
            Connection con = DriverManager.getConnection(url);
            String req = "select idClient,civiliteClient,nomClient,prenomClient from client";
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(req);
           
            Client ct1;
            //--stockage
            while(rs.next()){
                ct1 = new Client(rs.getInt(ICONIFIED),rs.getString("civiliteClient"),rs.getString("nomClient"),
                        rs.getString("prenomClient"));
                clientsList.add(ct1);
            }
        }
        catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
         return clientsList;
    }
    public void montrer_client(){
        ArrayList<Client> list = clientList();
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();
        Object[] row =new Object[4];
        row.toString();
        
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getIdClient();
            row[1] = list.get(i).getCivilite();
            row[2] = list.get(i).getNom();
            row[3] = list.get(i).getPrenom();
            model.addRow(row);
          

        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mamono = new javax.swing.JButton();
        MODIFIER = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        maTable = new javax.swing.JTable();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        name = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Bouton_Ajout = new javax.swing.JButton();
        list1 = new java.awt.List();
        list3 = new java.awt.List();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel1.setText("LIBRAIRIE EN LIGNE");

        mamono.setText("supprimer");
        mamono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mamonoActionPerformed(evt);
            }
        });

        MODIFIER.setText("modifier");
        MODIFIER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFIERActionPerformed(evt);
            }
        });

        jButton4.setText("afficher");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BACK OFFICE MANAGER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jTabbedPane1.addTab("Ouvrage", jTabbedPane2);

        maTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idClient", "civiliteClient", "NOM CLIENT", "PRENOM CLIENT"
            }
        ));
        jScrollPane1.setViewportView(maTable);

        jTabbedPane3.addTab("LISTE DE CLIENTS", jScrollPane1);

        jTabbedPane7.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel3.setText("civilite");

        jLabel4.setText("nomClient");

        jLabel5.setText("prenomClient");

        Bouton_Ajout.setText("AJOUTER");
        Bouton_Ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_AjoutActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madame", "Monsieur", "Mademoiselle" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(name)))
                .addGap(130, 130, 130)
                .addComponent(Bouton_Ajout)
                .addGap(48, 48, 48))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bouton_Ajout)
                        .addGap(26, 26, 26))))
        );

        jTabbedPane7.addTab("", panel1);

        jTabbedPane3.addTab("AJOUT DES CLIENTS", jTabbedPane7);

        jTabbedPane1.addTab("Client", jTabbedPane3);
        jTabbedPane1.addTab("Commande", jTabbedPane4);
        jTabbedPane1.addTab("Evenement", jTabbedPane5);
        jTabbedPane1.addTab("Avis", jTabbedPane6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mamono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MODIFIER, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(mamono)
                        .addGap(18, 18, 18)
                        .addComponent(MODIFIER)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(393, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mamonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mamonoActionPerformed
        //------------------------:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Librairie;"
                    + "user=sa;password=sa";
            Connection con = DriverManager.getConnection(url);
            int row = maTable.getSelectedRow();
            String value = (maTable.getModel().getValueAt(row,0).toString());
            String req = "DELETE from client where idClient =" + value;
            PreparedStatement pst = con.prepareStatement(req);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) maTable.getModel();
            model.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Suppression reussie!!!");
            montrer_client();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mamonoActionPerformed

    private void Bouton_AjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_AjoutActionPerformed
        
        String civilite = jComboBox1.getSelectedItem().toString();
        String Fname = name.getText();
        String Fprenom = prenom.getText();
        System.out.println("le rezu est civilite " + civilite + " nom "+ Fname+ ", prenom "+Fprenom+" ");
                
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Librairie;"
                    + "user=sa;password=sa";
            Connection con = DriverManager.getConnection(url);
            String req = "INSERT INTO client\n"
                    + "(civiliteClient, nomClient, prenomClient,telephoneClient,\n"
                    + " emailClient, motDePasseClient, dateAdhesionClient)\n"
                    + "VALUES\n"
                    + "(' "+civilite+"',' "+Fname+"',' "+Fprenom+"','0101010101',\n"
                    + "'Dupon@onconnaipas','duponmdp','2018-01-01')";
            PreparedStatement pst = con.prepareStatement(req);
            
            
           
            //pst.executeQuery(req);
            pst.execute();
            //montrer_client();
            JOptionPane.showMessageDialog(null, "Ajout reussi!!!");
             montrer_client();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Ajout NON reussi!!!");
               JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Bouton_AjoutActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void MODIFIERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFIERActionPerformed
        //------------je taf là
          try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Librairie;"
                    + "user=sa;password=sa";
            Connection con = DriverManager.getConnection(url);
            int row = maTable.getSelectedRow();
            String value = (maTable.getModel().getValueAt(row,0).toString());
            String req = "UPDATE client SET idClient=?, nomClient=?, prenomClient=?"+ value;
            PreparedStatement pst = con.prepareStatement(req);
              int idClient = 0;
            pst.setInt(ICONIFIED,idClient);
            pst.setString(1,name.getText());
            pst.setString(2,prenom.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) maTable.getModel();
            model.setRowCount(0);
            JOptionPane.showMessageDialog(null, "modif reussie!!!");
            montrer_client();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_MODIFIERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_Ajout;
    private javax.swing.JButton MODIFIER;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private java.awt.List list1;
    private java.awt.List list3;
    private javax.swing.JTable maTable;
    private javax.swing.JButton mamono;
    private javax.swing.JTextField name;
    private java.awt.Panel panel1;
    private javax.swing.JTextField prenom;
    // End of variables declaration//GEN-END:variables
}
